---
- name: This sets up an mysql server
  hosts: all
  tasks:
  - name: download remi-mysql repo
    get_url: url=http://rpms.famillecollet.com/enterprise/6/test/x86_64/compat-mysql55-5.5.11-1.el6.remi.x86_64.rpm dest=/tmp/compat-mysql5.5.11.remi.rpm
