---
- name: This sets up an mysql server
  hosts: all
  tasks:
  - name: Install MySQL 5.7 repo
    yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=installed
  
  - name: Install MySQL 5.7
    yum: pkg={{ item }}
    with_items:
      - mysql-community-server
      - MySQL-python
